views:
  - output: "about/index.html"
    template: "about.html"
  - output: "index.html"
    template: "landing.html"
  - output: "404.html"
    template: "404.html"

  - output: "statistics/index.html"
    query: "countries.rq"
    template: "statistics.html"
  - output: "statistics/statistics.svg"
    query: "countries.rq"
    template: "statistics.svg"
    unsafe: true

  - output: "topics/index.html"
    query: "topics.rq"
    template: "topic-list.html"
  - output: "{{safeName}}/index.html"
    query: "topics.rq"
    template: "topic-page.html"
  - output: "countries/index.html"
    query: "countries.rq"
    template: "country-list.html"
  - output: "{{safeName}}/index.html"
    query: "countries.rq"
    template: "country-page.html"

  - output: "sitemap.xml"
    query: "countries.rq"
    template: "sitemap.xml"
    unsafe: true

  - output: "map.json"
    query: "countries.rq"
    template: "map-data.json"
    unsafe: true
  - output: "countries/map/index.html"
    template: "countries-map.html"

# orgs

  - output: "greenland/{{qid}}/index.html"
    query: "generators/greenland.rq"
    template: "org.html"
  - output: "sweden/{{qid}}/index.html"
    query: "generators/sweden.rq"
    template: "org.html"
  - output: "united-kingdom/{{qid}}/index.html"
    query: "generators/united-kingdom.rq"
    template: "org.html"
  - output: "denmark/{{qid}}/index.html"
    query: "generators/denmark.rq"
    template: "org.html"
  - output: "norway/{{qid}}/index.html"
    query: "generators/norway.rq"
    template: "org.html"
  - output: "ghana/{{qid}}/index.html"
    query: "generators/ghana.rq"
    template: "org.html"
  - output: "germany/{{qid}}/index.html"
    query: "generators/germany.rq"
    template: "org.html"
  - output: "south-africa/{{qid}}/index.html"
    query: "generators/south-africa.rq"
    template: "org.html"
  - output: "netherlands/{{qid}}/index.html"
    query: "generators/netherlands.rq"
    template: "org.html"
  - output: "new-zealand/{{qid}}/index.html"
    query: "generators/new-zealand.rq"
    template: "org.html"
  - output: "finland/{{qid}}/index.html"
    query: "generators/finland.rq"
    template: "org.html"
  - output: "ukraine/{{qid}}/index.html"
    query: "generators/ukraine.rq"
    template: "org.html"
  - output: "russia/{{qid}}/index.html"
    query: "generators/russia.rq"
    template: "org.html"
  - output: "east-timor/{{qid}}/index.html"
    query: "generators/east-timor.rq"
    template: "org.html"
  - output: "philippines/{{qid}}/index.html"
    query: "generators/philippines.rq"
    template: "org.html"
  - output: "india/{{qid}}/index.html"
    query: "generators/india.rq"
    template: "org.html"
  - output: "belgium/{{qid}}/index.html"
    query: "generators/belgium.rq"
    template: "org.html"
  - output: "canada/{{qid}}/index.html"
    query: "generators/canada.rq"
    template: "org.html"
  - output: "indonesia/{{qid}}/index.html"
    query: "generators/indonesia.rq"
    template: "org.html"
  - output: "luxembourg/{{qid}}/index.html"
    query: "generators/luxembourg.rq"
    template: "org.html"
  - output: "singapore/{{qid}}/index.html"
    query: "generators/singapore.rq"
    template: "org.html"
  - output: "bermuda/{{qid}}/index.html"
    query: "generators/bermuda.rq"
    template: "org.html"
