# expected_result_count: 3638
SELECT DISTINCT
  ?qid
  ?orgLabel
  ?orgDescription
  ?type
  ?typeLabel
  ?country
WHERE {
  BIND(wd:Q219 AS ?country)
  {
    VALUES ?type {
      wd:Q136069342 # ministries (19)
      wd:Q12279293 # state agency (10)
      wd:Q121881025 # executive agency (32)
      wd:Q136410955 # independent government agency (16)
      wd:Q136405773 # administrative structures (48)
      wd:Q209824 # oblasts (28)
      wd:Q1906268 # municipalities (265)
      wd:Q4224624 # kmetstvo (3041)
      wd:Q7553685 # municipal districts (35)
    }
    ?org wdt:P31 ?type ;
         wdt:P17 ?country .
  }
  UNION
  {
    VALUES ?type {
      wd:Q136083525 # specialized local administration (144)
    }
    ?org wdt:P31/wdt:P279* ?type .
  }

  MINUS { ?org wdt:P576 [] }

  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  OPTIONAL { ?org rdfs:label ?orgLabelBg FILTER(LANG(?orgLabelBg) = "bg") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelMul, ?orgLabelBg, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescEn FILTER(LANG(?orgDescEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescMul FILTER(LANG(?orgDescMul) = "mul") }
  OPTIONAL { ?org schema:description ?orgDescBg FILTER(LANG(?orgDescBg) = "bg") }
  BIND(COALESCE(?orgDescEn, ?orgDescMul, ?orgDescBg) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  OPTIONAL { ?type rdfs:label ?typeLabelBg FILTER(LANG(?typeLabelBg) = "bg") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelMul, ?typeLabelBg, STR(?type)) AS ?typeLabel)
}
ORDER BY ?type ?orgLabel
