# expected_result_count: 429
SELECT DISTINCT
  ?qid
  ?orgLabel
  ?orgDescription
  ?type
  ?typeLabel
  ?country
WHERE {
  BIND(wd:Q33 AS ?country)
  {
  VALUES ?type {
    wd:Q193512 # Region (19)
    wd:Q10495402 # Ministries (12)
    wd:Q856076 # Municipalities (308)
  }
?org wdt:P31 ?type; wdt:P17 ?country .
}
UNION
{
  VALUES ?type {
    wd:Q2360219 # delegations (6)
    wd:Q372690 # consulate generals (5)
    wd:Q3917681 # embassies (77)
    wd:Q5244910 #  de facto embassy (1)
    wd:Q64779402 # liaison office (1)
}
?org wdt:P31 ?type; wdt:P137 ?country .
}
  MINUS { ?org wdt:P576 [] }
  MINUS { ?org wdt:P1366 [] }

  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelFi FILTER(LANG(?orgLabelFi) = "fi") }
  OPTIONAL { ?org rdfs:label ?orgLabelSv FILTER(LANG(?orgLabelSv) = "sv") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelFi, ?orgLabelSv, ?orgLabelMul, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescEn FILTER(LANG(?orgDescEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescFi FILTER(LANG(?orgDescFi) = "fi") }
  OPTIONAL { ?org schema:description ?orgDescSv FILTER(LANG(?orgDescSv) = "sv") }
  OPTIONAL { ?org schema:description ?orgDescMul FILTER(LANG(?orgDescMul) = "mul") }
  BIND(COALESCE(?orgDescEn, ?orgDescFi, ?orgDescSv, ?orgDescMul) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelFi FILTER(LANG(?typeLabelFi) = "fi") }
  OPTIONAL { ?type rdfs:label ?typeLabelSv FILTER(LANG(?typeLabelSv) = "sv") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelFi, ?typeLabelSv, ?typeLabelMul, STR(?type)) AS ?typeLabel)
}
ORDER BY ?type ?orgLabel
