# expected_result_count: 229
SELECT DISTINCT
?qid
?orgLabel
?orgDescription
?type
?typeLabel
?country
WHERE {
   BIND(wd:Q17 AS ?country)
{
  VALUES ?type {
    wd:Q15409298 # Ministries of Japan (11)
    wd:Q50337 # prefectures of Japan (47)
}
?org wdt:P31 ?type; wdt:P17 ?country .
}
UNION
{
  VALUES ?type {
    wd:Q3917681 # embassies (158)
    wd:Q2360219 # permanent missions (13)
}
?org wdt:P31 ?type; wdt:P137 ?country .
}
  MINUS { ?org wdt:P576 [] }
  MINUS { ?org wdt:P1366 [] }
  
  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  OPTIONAL { ?org rdfs:label ?orgLabelJa FILTER(LANG(?orgLabelJa) = "ja") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelMul, ?orgLabelJa, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescriptionEn FILTER(LANG(?orgDescriptionEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescriptionMul FILTER(LANG(?orgDescriptionMul) = "mul") }
  OPTIONAL { ?org schema:description ?orgDescriptionJa FILTER(LANG(?orgDescriptionJa) = "ja") }
  BIND(COALESCE(?orgDescriptionEn, ?orgDescriptionMul, ?orgDescriptionJa) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  OPTIONAL { ?type rdfs:label ?typeLabelJa FILTER(LANG(?typeLabelJa) = "ja") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelMul, ?typeLabelJa, STR(?type)) AS ?typeLabel)
}
ORDER BY ?typeLabel ?orgLabel