# expected_result_count: 431
SELECT DISTINCT
  ?qid
  ?orgLabel
  ?orgDescription
  ?type
  ?typeLabel
  ?country
WHERE {
  BIND(wd:Q1028 AS ?country)
{ 
  VALUES ?type {
    wd:Q20390905 # ministries (19)
    wd:Q121614922 # public institutions (228)
    wd:Q119811662   # regional councils (12)
    wd:Q15629582 # provinces (62)
    wd:Q15623950 # prefecture (13)
  }
  ?org wdt:P31 ?type .
  ?org wdt:P17 ?country .
} UNION {
  VALUES ?type { 
    wd:Q3917681 # embassies (97) 
  }
  ?org wdt:P31 ?type .
  ?org wdt:P137 ?country .
}
  
  MINUS { ?org wdt:P576 [] }
  MINUS { ?org wdt:P1366 [] }
  MINUS { ?org wdt:P3999 [] }
  MINUS { ?org wdt:P31 wd:Q19953632. }
  
  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelFr FILTER(LANG(?orgLabelFr) = "fr") }
  OPTIONAL { ?org rdfs:label ?orgLabelAr FILTER(LANG(?orgLabelAr) = "ar") }
  OPTIONAL { ?org rdfs:label ?orgLabelZgh FILTER(LANG(?orgLabelZgh) = "zgh") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelFr, ?orgLabelAr, ?orgLabelZgh, ?orgLabelMul, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescriptionEn FILTER(LANG(?orgDescriptionEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescriptionFr FILTER(LANG(?orgDescriptionFr) = "fr") }
  OPTIONAL { ?org schema:description ?orgDescriptionAr FILTER(LANG(?orgDescriptionAr) = "ar") }
  OPTIONAL { ?org schema:description ?orgDescriptionZgh FILTER(LANG(?orgDescriptionZgh) = "zgh") }
  OPTIONAL { ?org schema:description ?orgDescriptionMul FILTER(LANG(?orgDescriptionMul) = "mul") }
  BIND(COALESCE(?orgDescriptionEn, ?orgDescriptionFr, ?orgDescriptionAr, ?orgDescriptionZgh, ?orgDescriptionMul) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelFr FILTER(LANG(?typeLabelFr) = "fr") }
  OPTIONAL { ?type rdfs:label ?typeLabelAr FILTER(LANG(?typeLabelAr) = "ar") }
  OPTIONAL { ?type rdfs:label ?typeLabelZgh FILTER(LANG(?typeLabelZgh) = "zgh") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelFr, ?typeLabelAr, ?typeLabelZgh, ?typeLabelMul, STR(?type)) AS ?typeLabel)
}
ORDER BY ?type ?orgLabel
