# expected_result_count: 174
SELECT DISTINCT
  ?qid
  ?orgLabel
  ?orgDescription
  ?type
  ?typeLabel
  ?country
  ?cofog
WHERE {
  BIND(wd:Q664 AS ?country)

    # agencies with country set to New Zealand
    VALUES ?type {
      wd:Q116973815 # public service departments (31)
      wd:Q138750583 # non-public service departments (5)
      wd:Q130137120 # departemental agencies (7)
      wd:Q8041036 # wānanga (3)
      wd:Q130420294 # state-owned enterprise of New Zealand (12)
      wd:Q65600637 # regional council of New Zealand (11)
      wd:Q941036 # territorial authority of New Zealand (67)
      wd:Q125959397 # Autonomous Crown Entity (16)
      wd:Q126041101 # Independent Crown Entity (19)
      wd:Q134467041 # public research organisation (3)
    }

    ?org wdt:P31 ?type; wdt:P17 ?country .

  MINUS { ?org wdt:P576 [] }
  MINUS { ?org wdt:P1366 [] }
  MINUS { ?org wdt:P3999 [] }

  OPTIONAL {
    ?org wdt:P9798/wdt:P279* ?cofog .
    MINUS { ?cofog wdt:P279 [] }
  }

  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelMi FILTER(LANG(?orgLabelMi) = "mi") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelMi, ?orgLabelMul, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescriptionEn FILTER(LANG(?orgDescriptionEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescriptionMi FILTER(LANG(?orgDescriptionMi) = "mi") }
  OPTIONAL { ?org schema:description ?orgDescriptionMul FILTER(LANG(?orgDescriptionMul) = "mul") }
  BIND(COALESCE(?orgDescriptionEn, ?orgDescriptionMi, ?orgDescriptionMul) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelMi FILTER(LANG(?typeLabelMi) = "mi") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelMi, ?typeLabelMul, STR(?type)) AS ?typeLabel)
} ORDER BY ?typeLabel
