# expected_result_count: 22
SELECT DISTINCT
  ?qid
  ?orgLabel
  ?orgDescription
  ?type
  ?typeLabel
  ?country
WHERE {
  BIND(wd:Q159 AS ?country)

  VALUES ?type {
    wd:Q4481741 # ministries (21)
    wd:Q7188 # government (1)
  }
  ?org wdt:P31 ?type .

  ?org wdt:P17 ?country .
  MINUS { ?org wdt:P1366 [] }
  MINUS { ?org wdt:P576 ?ddate .
         MINUS { ?org wdt:P31 wd:Q4481741 ;
                       wdt:P576 ?ddate ;
                       wdt:P571 ?idate .
                FILTER ( ?idate > ?ddate )
               }
         }          

  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelRu FILTER(LANG(?orgLabelRu) = "ru") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelRu, ?orgLabelMul, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescriptionEn FILTER(LANG(?orgDescriptionEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescriptionRu FILTER(LANG(?orgDescriptionRu) = "ru") }
  OPTIONAL { ?org schema:description ?orgDescriptionMul FILTER(LANG(?orgDescriptionMul) = "mul") }
  BIND(COALESCE(?orgDescriptionEn, ?orgDescriptionRu, ?orgDescriptionMul) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelRu FILTER(LANG(?typeLabelRu) = "ru") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelRu, ?typeLabelMul, STR(?type)) AS ?typeLabel)
}
ORDER BY ?type ?orgLabel
