# expected_result_count: 41
SELECT DISTINCT
  ?qid
  ?orgLabel
  ?orgDescription
  ?type
  ?typeLabel
  ?country
WHERE {
  BIND(wd:Q334 AS ?country)

  VALUES ?type {
    wd:Q35749 # Parliament of Singapore (1)
    wd:Q1320217 # Government of Singapore (1)
    wd:Q190752 # Supreme Court of Singapore (1)
    wd:Q112818479 # Ministries (16)
    wd:Q3507268 # Town Councils (17)
    wd:Q4426538  # Community Development Council Districts (5)
  }
  ?org wdt:P31 ?type .

  ?org wdt:P17 ?country .

  MINUS { ?org wdt:P576 [] }
  MINUS { ?org wdt:P1366 [] }

  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelTl FILTER(LANG(?orgLabelTl) = "tl") }
  OPTIONAL { ?org rdfs:label ?orgLabelMs FILTER(LANG(?orgLabelMs) = "ms") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelTl, ?orgLabelMs, ?orgLabelMul, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescriptionEn FILTER(LANG(?orgDescriptionEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescriptionTl FILTER(LANG(?orgDescriptionTl) = "tl") }
  OPTIONAL { ?org schema:description ?orgDescriptionMs FILTER(LANG(?orgDescriptionMs) = "ms") }
  OPTIONAL { ?org schema:description ?orgDescriptionMul FILTER(LANG(?orgDescriptionMul) = "mul") }
  BIND(COALESCE(?orgDescriptionEn, ?orgDescriptionTl, ?orgDescriptionMs, ?orgDescriptionMul) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelTl FILTER(LANG(?typeLabelTl) = "tl") }
  OPTIONAL { ?type rdfs:label ?typeLabelMs FILTER(LANG(?typeLabelMs) = "ms") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelTl, ?typeLabelMs, ?typeLabelMul, STR(?type)) AS ?typeLabel)
}
ORDER BY ?type ?orgLabel
