# TODO statements having multiply values
SELECT DISTINCT ?qid ?orgLabel ?orgDescription ?website ?typeLabel WHERE {
  VALUES ?type {
    wd:Q127448 # municipality of Sweden (290)
    wd:Q1754161 # regional council in Sweden (21)
    wd:Q341627 # court of appeal(hovrätten) (6)
    wd:Q196321 # county administrative board (21)
  }
  ?org wdt:P31 ?type .

  ?org wdt:P17 wd:Q34 .
  OPTIONAL { ?org wdt:P856 ?website }
  OPTIONAL { ?org wdt:P968 ?email }
  
  MINUS { ?org wdt:P576 [] }

  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE]". }
} ORDER BY ?type