# expected_result_count: 2154
SELECT DISTINCT
  ?qid
  ?orgLabel
  ?orgDescription
  ?type
  ?typeLabel
  ?country
WHERE {
  BIND(wd:Q39 AS ?country)

  VALUES ?type {
    wd:Q113015553 # federal ministry of switzerland (7)
    wd:Q23058 # canton of switzerland (26)
    wd:Q70208 # municipality of Switzerland (2121)
  }
  ?org wdt:P31 ?type .

  ?org wdt:P17 ?country .

  MINUS { ?org wdt:P576 [] }
  MINUS { ?org wdt:P1366 [] }
  MINUS { ?org wdt:P582 [] }
  MINUS { ?org wdt:P571 ?date . FILTER (DATATYPE(?date) = xsd:dateTime && ?date > now()) }


  BIND(REPLACE(STR(?org), "http://www.wikidata.org/entity/", "") AS ?qid)

  OPTIONAL { ?org rdfs:label ?orgLabelEn FILTER(LANG(?orgLabelEn) = "en") }
  OPTIONAL { ?org rdfs:label ?orgLabelDe FILTER(LANG(?orgLabelDe) = "de") }
  OPTIONAL { ?org rdfs:label ?orgLabelFr FILTER(LANG(?orgLabelFr) = "fr") }
  OPTIONAL { ?org rdfs:label ?orgLabelIt FILTER(LANG(?orgLabelIt) = "it") }
  OPTIONAL { ?org rdfs:label ?orgLabelMul FILTER(LANG(?orgLabelMul) = "mul") }
  BIND(COALESCE(?orgLabelEn, ?orgLabelDe, ?orgLabelFr, ?orgLabelIt, ?orgLabelMul, STR(?org)) AS ?orgLabel)

  OPTIONAL { ?org schema:description ?orgDescriptionEn FILTER(LANG(?orgDescriptionEn) = "en") }
  OPTIONAL { ?org schema:description ?orgDescriptionDe FILTER(LANG(?orgDescriptionDe) = "de") }
  OPTIONAL { ?org schema:description ?orgDescriptionFr FILTER(LANG(?orgDescriptionFr) = "fr") }
  OPTIONAL { ?org schema:description ?orgDescriptionIt FILTER(LANG(?orgDescriptionIt) = "it") }
  OPTIONAL { ?org schema:description ?orgDescriptionMul FILTER(LANG(?orgDescriptionMul) = "mul") }
  BIND(COALESCE(?orgDescriptionEn, ?orgDescriptionDe, ?orgDescriptionFr, ?orgDescriptionIt, ?orgDescriptionMul) AS ?orgDescription)

  OPTIONAL { ?type rdfs:label ?typeLabelEn FILTER(LANG(?typeLabelEn) = "en") }
  OPTIONAL { ?type rdfs:label ?typeLabelDe FILTER(LANG(?typeLabelDe) = "de") }
  OPTIONAL { ?type rdfs:label ?typeLabelFr FILTER(LANG(?typeLabelFr) = "fr") }
  OPTIONAL { ?type rdfs:label ?typeLabelIt FILTER(LANG(?typeLabelIt) = "it") }
  OPTIONAL { ?type rdfs:label ?typeLabelMul FILTER(LANG(?typeLabelMul) = "mul") }
  BIND(COALESCE(?typeLabelEn, ?typeLabelDe, ?typeLabelFr, ?typeLabelIt, ?typeLabelMul, STR(?type)) AS ?typeLabel)
}
ORDER BY ?type ?orgLabel
