SELECT 
  (SAMPLE(?website_) AS ?website)
  (SAMPLE(?email_) AS ?email)
  (SAMPLE(?citizensInitiatives_) AS ?citizensInitiatives)
  (SAMPLE(?foiUrl_) AS ?foiUrl)
  (SAMPLE(?contactPage_) AS ?contactPage)
  (SAMPLE(?regulatoryText_) AS ?regulatoryText)
  (SAMPLE(?regulatoryTextTitle_) AS ?regulatoryTextTitle)
  (SAMPLE(?phone_) AS ?phone)
  (SAMPLE(?ledByLabel_) AS ?ledByLabel)
  (SAMPLE(?latestStart_) AS ?latestStart)
  (SAMPLE(?wikipedia_) AS ?wikipedia)

WHERE {
  VALUES ?org { wd:{{.}} }

  OPTIONAL {
    # ensures we get the most relevant(the latest) position
    ?org wdt:P1313 ?position .
    {
      SELECT ?position (MAX(?startDate) AS ?latestStart_) WHERE {
        ?ledBy wdt:P31 wd:Q5 .
        ?ledBy p:P39 ?posStatement .
        ?posStatement ps:P39 ?position .
        ?posStatement pq:P580 ?startDate .
        FILTER NOT EXISTS { ?posStatement pq:P582 ?endDate . }
      }
      GROUP BY ?position
    }
    OPTIONAL {
      ?ledBy wdt:P31 wd:Q5 .
      ?ledBy p:P39 ?posStatement .
      ?posStatement ps:P39 ?position .
      ?posStatement pq:P580 ?latestStart_ .
      FILTER NOT EXISTS { ?posStatement pq:P582 ?endDate . }
      OPTIONAL { ?ledBy rdfs:label ?ledByLabelEn . FILTER(LANG(?ledByLabelEn) = "en") }
      OPTIONAL { ?ledBy rdfs:label ?ledByLabelSv . FILTER(LANG(?ledByLabelSv) = "sv") }
      OPTIONAL { ?ledBy rdfs:label ?ledByLabelMul . FILTER(LANG(?ledByLabelMul) = "mul") }
      BIND(COALESCE(?ledByLabelEn, ?ledByLabelSv, ?ledByLabelMul, STR(?ledBy)) AS ?ledByLabel_)
    }
  }

  OPTIONAL { ?org wdt:P856 ?website_ }
  OPTIONAL { ?org wdt:P968 ?email_ }
  OPTIONAL { ?org wdt:P9732 ?citizensInitiatives_ }
  OPTIONAL { ?org wdt:P10214 ?foiUrl_ }
  OPTIONAL { ?org wdt:P11266 ?contactPage_ }

  OPTIONAL {
    ?org wdt:P92 ?regulatoryTextItem .
    ?regulatoryTextItem wdt:P953 ?regulatoryText_ ;
                        wdt:P1476 ?regulatoryTextTitle_ .
  }

  OPTIONAL {
    ?org wdt:P1329 ?phone_ .
    ?org p:P1329 ?phone_Statement .
    ?phone_Statement (ps:P1329) [] .
    FILTER(EXISTS { ?phone_Statement prov:wasDerivedFrom ?reference. })
  }

  OPTIONAL {
    ?wikipedia_ schema:about ?org ;
               schema:isPartOf <https://en.wikipedia.org/> .
  }
}
