SELECT DISTINCT * WHERE {
  VALUES (?safeName ?name) {
    ("defense" "Defense")
    ("environmental-protection" "Environmental protection")
    ("health" "Health")
    ("education" "Education")
  }
} ORDER BY ?class
